### ISSUE TITLE
API Certificate Expired

### ISSUE THREAD

**Issue by treesta1ker** [Weldawadyathink/Audiobook-Covers#37]
The Let's Encrypt certificate used for the API (https://api.audiobookcovers.com) expired on Wed, 03 Jul 2024 06:35:05 GMT. This is preventing services like [Audiobookshelf](https://github.com/advplyr/audiobookshelf) from being able to search and pull book covers.

**Comment by Weldawadyathink** [comment]
Oh certificates. This has broken twice since I got it functioning and both times it has been certificates. FUN!

Anyway thanks for the info. I would just love if GitHub would actually alert me about these issues.

**Comment by Weldawadyathink** [comment]
Rewrite is almost complete, but functional enough to redeploy, so this should be fixed. Let me know if you still get issues.
