### ISSUE TITLE
DNS Routing

### ISSUE THREAD

**Issue by treesta1ker** [Weldawadyathink/Audiobook-Covers#40]
There seems to be an issue with the DNS routing for the host used by [Audiobookshelf](https://github.com/advplyr/audiobookshelf) (ie `api.audiobookcovers.com`). 
The ABS code can be found  [here](https://github.com/advplyr/audiobookshelf/blob/52a3bc224ae7c79fbb543716a25b731c65a8f76a/server/providers/AudiobookCovers.js#L18).

Using a browser, https://api.audiobookcovers.com/cover/bytext/ results in 404 error page (from vercel).  However, https://www.audiobookcovers.com/cover/bytext/ results in the expected API response (400 with the string `Query parameter missing`).

Also, it appears the master branch of this repo is not currently deployed, but rather [next-rewrite](https://github.com/Weldawadyathink/Audiobook-Covers/tree/next-rewrite). If that is intentionally and the desired functionality going forward, it would be beneficial to contributors to merge the [next-rewrite](https://github.com/Weldawadyathink/Audiobook-Covers/tree/next-rewrite) branch into master.

**Comment by Weldawadyathink** [comment]
Thanks for the report. It looks like vercel throws a fit if you cname to a vercel website but don't explicitly add that domain. It should me working now. Let me know if you have any issues. 

next-rewrite branch was my ill fated attempt to append my rewrite change history into the main branch. I should have started the rewrite in a branch on this repo, but I made the mistake of starting a completely new git repo. I figured I could just pull request the changes over, but if one repo isn't associated with another repo, you can't do that. Either way, its cleaned up now, although loosing the git history is a bummer.
